import { env } from "@/../env";
import { resend } from "@/lib/resend";
import { MonitoringAlertEmail } from "@/lib/resend/emails";
import { getAbsoluteURL } from "@/lib/utils";
import { sendPlainWhatsAppMessage } from "@/lib/whatsapp";
import {
    and,
    desc,
    eq,
    gte,
    inArray,
    isNotNull,
    isNull,
    lt,
    ne,
    or,
    sql,
} from "drizzle-orm";
import { db } from "..";
import {
    accessReviewItems,
    accessReviewRuns,
    auditLogs,
    brandConfidentials,
    brandRequests,
    brands,
    carrierClaims,
    codReconciliationItems,
    codReconciliationRuns,
    complianceExportFiles,
    complianceExportRuns,
    dailyHealthSnapshots,
    fraudReviews,
    monitoringAlertDeliveries,
    monitoringAlertEvents,
    monitoringAlerts,
    orderItems,
    orderReturnRequests,
    orders,
    orderShipments,
    products,
    productVariants,
    refunds,
    rtoDispositions,
    slaCheckRuns,
    supportTickets,
    userRoles,
    users,
    userSupportTickets,
    weeklyReportingPacks,
} from "../schema";
import { auditLogQueries, type AuditLogInput } from "./audit-log";

type AlertSeverity = "info" | "warning" | "critical";
type AlertChannel = "whatsapp" | "email" | "admin";

export type ComplianceExportRow = Record<string, unknown>;
export type ComplianceExportFile = {
    name: string;
    rowCount: number;
    headers: string[];
};
export type ComplianceExportBuild = {
    rows: ComplianceExportRow[];
    csv: string;
    files: ComplianceExportFile[];
    headers: string[];
};

type AlertInput = {
    type: string;
    severity: AlertSeverity;
    entityType: string;
    entityId: string;
    title: string;
    message: string;
    ownerId?: string | null;
    ownerRole?: string | null;
    channels?: AlertChannel[];
    recipients?: string[];
    dueAt?: Date | null;
    acknowledgedDueAt?: Date | null;
    dedupeKey: string;
    metadata?: Record<string, unknown>;
};

type AlertAction = {
    alertId: string;
    actorId?: string | null;
    reasonCode?: string | null;
    notes?: string | null;
};

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
const ALERT_RECIPIENTS = [
    process.env.RENIVET_ALERT_EMAIL,
    process.env.RENIVET_EMAIL_1,
    process.env.RENIVET_EMAIL_2,
].filter(Boolean) as string[];
const ALERT_WHATSAPP_RECIPIENTS = (process.env.RENIVET_ALERT_WHATSAPP ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
const MONITORING_DASHBOARD_PATH = "/dashboard/general/monitoring-sla";

function formatAlertDate(value?: Date | string | null) {
    if (!value) return "Not set";

    const date = value instanceof Date ? value : new Date(value);
    if (Number.isNaN(date.getTime())) return "Not set";

    return new Intl.DateTimeFormat("en-IN", {
        dateStyle: "medium",
        timeStyle: "short",
        timeZone: "Asia/Kolkata",
    }).format(date);
}

function buildAlertPlainText(alert: typeof monitoringAlerts.$inferSelect) {
    return [
        `[${alert.severity.toUpperCase()}] ${alert.title}`,
        "",
        alert.message,
        "",
        `Alert type: ${alert.type}`,
        `Entity: ${alert.entityType} ${alert.entityId}`,
        `Acknowledge by: ${formatAlertDate(alert.acknowledgedDueAt)}`,
        `Resolve by: ${formatAlertDate(alert.dueAt)}`,
        "",
        `Open dashboard: ${getAbsoluteURL(MONITORING_DASHBOARD_PATH)}`,
        "",
        "This automated alert was generated by Renivet monitoring.",
    ].join("\n");
}
const ACTIVE_SUPPORT_STATUSES = [
    "new",
    "acknowledged",
    "in_progress",
    "waiting_customer",
    "waiting_brand",
    "waiting_internal",
    "reopened",
    "escalated",
    "open",
    "pending",
    "in_review",
    "waiting_for_customer",
    "waiting_for_brand",
    "approved",
];

function startOfDay(date = new Date()) {
    const d = new Date(date);
    d.setHours(0, 0, 0, 0);
    return d;
}

function monthWindow(month: string) {
    const [year, monthIndex] = month.split("-").map(Number);
    const start = new Date(year, monthIndex - 1, 1);
    const end = new Date(year, monthIndex, 1);
    return { start, end };
}

function addYears(date: Date, years: number) {
    const d = new Date(date);
    d.setFullYear(d.getFullYear() + years);
    return d;
}

function csvEscape(value: unknown) {
    const text = value === null || value === undefined ? "" : String(value);
    const quote = String.fromCharCode(34);
    return `${quote}${text.replaceAll(quote, quote + quote)}${quote}`;
}

function toCsv<T extends Record<string, unknown>>(
    rows: T[],
    headers?: string[]
) {
    const csvHeaders = headers ?? Object.keys(rows[0] ?? {});
    if (!csvHeaders.length) return "";
    return [
        csvHeaders.map(csvEscape).join(","),
        ...rows.map((row) =>
            csvHeaders.map((header) => csvEscape(row[header])).join(",")
        ),
    ].join("\n");
}

class MonitoringSlaQuery {
    async writeAudit(input: AuditLogInput) {
        return auditLogQueries.write(input);
    }

    async createAlert(input: AlertInput) {
        const existing = await db.query.monitoringAlerts.findFirst({
            where: and(
                eq(monitoringAlerts.dedupeKey, input.dedupeKey),
                inArray(monitoringAlerts.status, [
                    "open",
                    "acknowledged",
                    "escalated",
                ])
            ),
        });

        if (existing) return existing;

        const channels: AlertChannel[] = input.channels?.length
            ? input.channels
            : input.severity === "info"
              ? ["admin"]
              : ["admin", "email"];
        const recipients = input.recipients?.length
            ? input.recipients
            : ALERT_RECIPIENTS;
        const now = new Date();

        const alert = await db
            .insert(monitoringAlerts)
            .values({
                ...input,
                channels,
                recipients,
                acknowledgedDueAt:
                    input.acknowledgedDueAt ??
                    new Date(
                        now.getTime() +
                            (input.severity === "critical" ? 2 : 4) * HOUR
                    ),
            })
            .returning()
            .then((res) => res[0]);

        await db.insert(monitoringAlertEvents).values({
            alertId: alert.id,
            action: "created",
            actorId: input.ownerId,
            metadata: input.metadata ?? {},
        });

        await this.writeAudit({
            userId: input.ownerId,
            actionType: "alert_created",
            entityType: input.entityType,
            entityId: input.entityId,
            afterValue: {
                alertId: alert.id,
                severity: alert.severity,
                title: alert.title,
                channels,
                recipients,
            },
            reason: input.type,
            metadata: input.metadata ?? {},
        });

        await this.dispatchAlert(alert.id);
        return alert;
    }

    async dispatchAlert(alertId: string) {
        const alert = await db.query.monitoringAlerts.findFirst({
            where: eq(monitoringAlerts.id, alertId),
        });
        if (!alert) return [];

        const channels = alert.channels?.length ? alert.channels : ["admin"];
        const emailRecipients = alert.recipients?.length
            ? alert.recipients
            : ALERT_RECIPIENTS;
        const deliveries = [];

        if (channels.includes("admin")) {
            deliveries.push(
                await db
                    .insert(monitoringAlertDeliveries)
                    .values({
                        alertId,
                        channel: "admin",
                        recipient: "alert-center",
                        status: "sent",
                        sentAt: new Date(),
                    })
                    .returning()
                    .then((res) => res[0])
            );
        }

        if (channels.includes("email")) {
            for (const recipient of emailRecipients) {
                try {
                    const sent = await resend.emails.send({
                        from: env.RESEND_EMAIL_FROM,
                        to: recipient,
                        subject: `[${alert.severity.toUpperCase()}] ${alert.title}`,
                        react: MonitoringAlertEmail({
                            severity: alert.severity,
                            title: alert.title,
                            message: alert.message,
                            entityType: alert.entityType,
                            entityId: alert.entityId,
                            alertType: alert.type,
                            dueAt: alert.dueAt,
                            acknowledgedDueAt: alert.acknowledgedDueAt,
                            href: MONITORING_DASHBOARD_PATH,
                        }),
                        text: buildAlertPlainText(alert),
                    });
                    deliveries.push(
                        await db
                            .insert(monitoringAlertDeliveries)
                            .values({
                                alertId,
                                channel: "email",
                                recipient,
                                status: sent.error ? "failed" : "sent",
                                providerMessageId: sent.data?.id,
                                error: sent.error?.message,
                                sentAt: sent.error ? undefined : new Date(),
                            })
                            .returning()
                            .then((res) => res[0])
                    );
                } catch (error) {
                    deliveries.push(
                        await db
                            .insert(monitoringAlertDeliveries)
                            .values({
                                alertId,
                                channel: "email",
                                recipient,
                                status: "failed",
                                error:
                                    error instanceof Error
                                        ? error.message
                                        : "Email send failed",
                            })
                            .returning()
                            .then((res) => res[0])
                    );
                }
            }
        }

        if (channels.includes("whatsapp")) {
            for (const recipient of ALERT_WHATSAPP_RECIPIENTS) {
                try {
                    const sent = await sendPlainWhatsAppMessage({
                        recipientPhoneNumber: recipient,
                        message: `[${alert.severity.toUpperCase()}] ${alert.title}\n${alert.message}`,
                    });
                    deliveries.push(
                        await db
                            .insert(monitoringAlertDeliveries)
                            .values({
                                alertId,
                                channel: "whatsapp",
                                recipient,
                                status: "sent",
                                providerMessageId: sent.data?.sid,
                                sentAt: new Date(),
                            })
                            .returning()
                            .then((res) => res[0])
                    );
                } catch (error) {
                    deliveries.push(
                        await db
                            .insert(monitoringAlertDeliveries)
                            .values({
                                alertId,
                                channel: "whatsapp",
                                recipient,
                                status: "failed",
                                error:
                                    error instanceof Error
                                        ? error.message
                                        : "WhatsApp send failed",
                            })
                            .returning()
                            .then((res) => res[0])
                    );
                }
            }
        }

        return deliveries;
    }

    async updateAlertStatus(
        status: "acknowledged" | "escalated" | "resolved",
        input: AlertAction
    ) {
        const before = await db.query.monitoringAlerts.findFirst({
            where: eq(monitoringAlerts.id, input.alertId),
        });
        const now = new Date();
        const values =
            status === "acknowledged"
                ? {
                      status,
                      acknowledgedBy: input.actorId,
                      acknowledgedAt: now,
                      reasonCode: input.reasonCode,
                      notes: input.notes,
                  }
                : status === "escalated"
                  ? {
                        status,
                        escalatedBy: input.actorId,
                        escalatedAt: now,
                        reasonCode: input.reasonCode,
                        notes: input.notes,
                    }
                  : {
                        status,
                        resolvedBy: input.actorId,
                        resolvedAt: now,
                        reasonCode: input.reasonCode,
                        notes: input.notes,
                    };

        const alert = await db
            .update(monitoringAlerts)
            .set(values)
            .where(eq(monitoringAlerts.id, input.alertId))
            .returning()
            .then((res) => res[0]);

        if (alert) {
            await db.insert(monitoringAlertEvents).values({
                alertId: input.alertId,
                action: status,
                actorId: input.actorId,
                reasonCode: input.reasonCode,
                notes: input.notes,
            });
            await this.writeAudit({
                userId: input.actorId,
                actionType: `alert_${status}`,
                entityType: alert.entityType,
                entityId: alert.entityId,
                beforeValue: before ? { status: before.status } : null,
                afterValue: { status: alert.status },
                reason: input.reasonCode ?? input.notes,
                metadata: { alertId: alert.id },
            });
        }

        return alert;
    }

    async getActiveAlerts(limit = 50, offset = 0, severity?: AlertSeverity) {
        return db.query.monitoringAlerts.findMany({
            where: and(
                ne(monitoringAlerts.status, "resolved"),
                severity ? eq(monitoringAlerts.severity, severity) : undefined
            ),
            orderBy: [
                desc(monitoringAlerts.severity),
                desc(monitoringAlerts.createdAt),
            ],
            limit,
            offset,
        });
    }

    async getActiveAlertsPage(
        page = 1,
        pageSize = 10,
        severity?: AlertSeverity
    ) {
        const safePage = Math.max(1, page);
        const safePageSize = Math.min(Math.max(5, pageSize), 50);
        const total = await db.$count(
            monitoringAlerts,
            and(
                ne(monitoringAlerts.status, "resolved"),
                severity ? eq(monitoringAlerts.severity, severity) : undefined
            )
        );
        const rows = await this.getActiveAlerts(
            safePageSize,
            (safePage - 1) * safePageSize,
            severity
        );

        return {
            rows,
            total,
            page: safePage,
            pageSize: safePageSize,
            pageCount: Math.max(1, Math.ceil(total / safePageSize)),
        };
    }

    async getAlertSummary() {
        return db
            .select({
                status: monitoringAlerts.status,
                severity: monitoringAlerts.severity,
                count: sql<number>`count(*)`,
            })
            .from(monitoringAlerts)
            .groupBy(monitoringAlerts.status, monitoringAlerts.severity);
    }

    async runSlaCheck(actorId?: string | null) {
        const runKey = `sla-${new Date().toISOString().slice(0, 13)}`;
        const existingRun = await db.query.slaCheckRuns.findFirst({
            where: eq(slaCheckRuns.runKey, runKey),
        });
        if (existingRun?.status === "completed") return existingRun;

        const run =
            existingRun ??
            (await db
                .insert(slaCheckRuns)
                .values({ runKey, status: "running" })
                .returning()
                .then((res) => res[0]));
        if (!run) throw new Error("Unable to create SLA check run");

        const now = new Date();
        const twoHourCutoff = new Date(now.getTime() - 2 * HOUR);
        const fourHourCutoff = new Date(now.getTime() - 4 * HOUR);
        const sixHourCutoff = new Date(now.getTime() - 6 * HOUR);
        const eighteenHourCutoff = new Date(now.getTime() - 18 * HOUR);
        const dayCutoff = new Date(now.getTime() - DAY);
        const twoDayCutoff = new Date(now.getTime() - 2 * DAY);
        const threeDayCutoff = new Date(now.getTime() - 3 * DAY);
        const sevenDayCutoff = new Date(now.getTime() - 7 * DAY);
        const fourteenDayCutoff = new Date(now.getTime() - 14 * DAY);
        const fortyFiveDayCutoff = new Date(now.getTime() - 45 * DAY);
        const thirtyDayCutoff = new Date(now.getTime() + 30 * DAY);
        const thirtyDaysAgo = new Date(now.getTime() - 30 * DAY);
        let checkedCount = 0;
        let breachCount = 0;

        const unassignedTickets = await db
            .select({
                id: supportTickets.id,
                title: supportTickets.title,
                createdAt: supportTickets.createdAt,
            })
            .from(supportTickets)
            .where(
                and(
                    inArray(supportTickets.status, ACTIVE_SUPPORT_STATUSES),
                    isNull(supportTickets.assignedAdminId),
                    lt(supportTickets.createdAt, twoHourCutoff)
                )
            )
            .limit(100);

        const staleAdminTickets = await db
            .select({
                id: supportTickets.id,
                title: supportTickets.title,
                statusChangedAt: supportTickets.statusChangedAt,
            })
            .from(supportTickets)
            .where(
                and(
                    inArray(supportTickets.status, ACTIVE_SUPPORT_STATUSES),
                    lt(supportTickets.statusChangedAt, dayCutoff)
                )
            )
            .limit(100);

        const staleUserTickets = await db
            .select({
                id: userSupportTickets.id,
                title: userSupportTickets.title,
                statusChangedAt: userSupportTickets.statusChangedAt,
            })
            .from(userSupportTickets)
            .where(
                and(
                    inArray(userSupportTickets.status, ACTIVE_SUPPORT_STATUSES),
                    lt(userSupportTickets.statusChangedAt, dayCutoff)
                )
            )
            .limit(100);

        const adminFirstResponseBreaches = await db
            .select({
                id: supportTickets.id,
                title: supportTickets.title,
                dueAt: supportTickets.firstResponseDueAt,
            })
            .from(supportTickets)
            .where(
                and(
                    inArray(supportTickets.status, ACTIVE_SUPPORT_STATUSES),
                    isNotNull(supportTickets.firstResponseDueAt),
                    isNull(supportTickets.firstRespondedAt),
                    lt(supportTickets.firstResponseDueAt, now)
                )
            )
            .limit(100);

        const userFirstResponseBreaches = await db
            .select({
                id: userSupportTickets.id,
                title: userSupportTickets.title,
                dueAt: userSupportTickets.firstResponseDueAt,
            })
            .from(userSupportTickets)
            .where(
                and(
                    inArray(userSupportTickets.status, ACTIVE_SUPPORT_STATUSES),
                    isNotNull(userSupportTickets.firstResponseDueAt),
                    isNull(userSupportTickets.firstRespondedAt),
                    lt(userSupportTickets.firstResponseDueAt, now)
                )
            )
            .limit(100);

        const adminResolutionBreaches = await db
            .select({
                id: supportTickets.id,
                title: supportTickets.title,
                dueAt: supportTickets.resolutionDueAt,
            })
            .from(supportTickets)
            .where(
                and(
                    inArray(supportTickets.status, ACTIVE_SUPPORT_STATUSES),
                    isNotNull(supportTickets.resolutionDueAt),
                    lt(supportTickets.resolutionDueAt, now)
                )
            )
            .limit(100);

        const userResolutionBreaches = await db
            .select({
                id: userSupportTickets.id,
                title: userSupportTickets.title,
                dueAt: userSupportTickets.resolutionDueAt,
            })
            .from(userSupportTickets)
            .where(
                and(
                    inArray(userSupportTickets.status, ACTIVE_SUPPORT_STATUSES),
                    isNotNull(userSupportTickets.resolutionDueAt),
                    lt(userSupportTickets.resolutionDueAt, now)
                )
            )
            .limit(100);

        const missedCustomerUpdates = await db
            .select({
                id: userSupportTickets.id,
                title: userSupportTickets.title,
                dueAt: userSupportTickets.nextCustomerUpdateDueAt,
            })
            .from(userSupportTickets)
            .where(
                and(
                    inArray(userSupportTickets.status, ACTIVE_SUPPORT_STATUSES),
                    isNotNull(userSupportTickets.nextCustomerUpdateDueAt),
                    lt(userSupportTickets.nextCustomerUpdateDueAt, now)
                )
            )
            .limit(100);

        const customerAutoCloseTickets = await db
            .select({
                id: userSupportTickets.id,
                title: userSupportTickets.title,
                autoCloseEligibleAt: userSupportTickets.autoCloseEligibleAt,
            })
            .from(userSupportTickets)
            .where(
                and(
                    eq(userSupportTickets.status, "waiting_customer"),
                    isNotNull(userSupportTickets.autoCloseEligibleAt),
                    lt(userSupportTickets.autoCloseEligibleAt, now)
                )
            )
            .limit(100);

        const unackOrders24 = await db
            .select({ id: orders.id, createdAt: orders.createdAt })
            .from(orders)
            .where(
                and(
                    inArray(orders.status, ["pending", "processing"]),
                    isNull(orders.brandAcknowledgedAt),
                    lt(orders.createdAt, dayCutoff)
                )
            )
            .limit(100);

        const brandAckAtRisk18 = await db
            .select({ id: orders.id, createdAt: orders.createdAt })
            .from(orders)
            .where(
                and(
                    inArray(orders.status, ["pending", "processing"]),
                    isNull(orders.brandAcknowledgedAt),
                    lt(orders.createdAt, eighteenHourCutoff),
                    gte(orders.createdAt, dayCutoff)
                )
            )
            .limit(100);

        const brandSilenceAutoCancels = await db
            .select({
                id: orders.id,
                createdAt: orders.createdAt,
                paymentStatus: orders.paymentStatus,
                status: orders.status,
            })
            .from(orders)
            .where(
                and(
                    inArray(orders.status, ["pending", "processing"]),
                    isNull(orders.brandAcknowledgedAt),
                    lt(orders.createdAt, twoDayCutoff)
                )
            )
            .limit(100);

        const stuckOrders = await db
            .select({ id: orders.id, updatedAt: orders.updatedAt })
            .from(orders)
            .where(
                and(
                    inArray(orders.status, ["pending", "processing"]),
                    lt(orders.updatedAt, twoDayCutoff)
                )
            )
            .limit(100);

        const stuckOrders72 = await db
            .select({
                id: orders.id,
                status: orders.status,
                updatedAt: orders.updatedAt,
            })
            .from(orders)
            .where(
                and(
                    inArray(orders.status, [
                        "pending",
                        "processing",
                        "shipped",
                    ]),
                    lt(orders.updatedAt, threeDayCutoff)
                )
            )
            .limit(100);

        const codFraudReviewBreaches = await db
            .select({
                id: fraudReviews.orderId,
                reviewId: fraudReviews.id,
                createdAt: fraudReviews.createdAt,
                totalAmount: orders.totalAmount,
            })
            .from(fraudReviews)
            .innerJoin(orders, eq(orders.id, fraudReviews.orderId))
            .where(
                and(
                    eq(fraudReviews.status, "pending"),
                    or(
                        lt(fraudReviews.dueAt, now),
                        lt(fraudReviews.createdAt, fourHourCutoff)
                    )
                )
            )
            .limit(100);

        const staleTrackingShipments = await db
            .select({
                id: orderShipments.id,
                orderId: orderShipments.orderId,
                status: orderShipments.status,
                updatedAt: orderShipments.updatedAt,
            })
            .from(orderShipments)
            .where(
                and(
                    inArray(orderShipments.status, [
                        "in_transit",
                        "out_for_delivery",
                    ]),
                    lt(orderShipments.updatedAt, sixHourCutoff)
                )
            )
            .limit(100);

        const rtoDispositionBreaches = await db
            .select({
                id: rtoDispositions.id,
                orderId: rtoDispositions.orderId,
                status: rtoDispositions.status,
                updatedAt: rtoDispositions.updatedAt,
            })
            .from(rtoDispositions)
            .where(
                and(
                    inArray(rtoDispositions.status, ["pending", "recovering"]),
                    or(
                        lt(rtoDispositions.dispositionDueAt, now),
                        lt(rtoDispositions.createdAt, sevenDayCutoff)
                    )
                )
            )
            .limit(100);

        const returnQcBreaches = await db
            .select({
                id: orderReturnRequests.id,
                orderId: orderReturnRequests.orderId,
                updatedAt: orderReturnRequests.updatedAt,
            })
            .from(orderReturnRequests)
            .where(
                and(
                    eq(orderReturnRequests.status, "processing"),
                    lt(orderReturnRequests.updatedAt, twoDayCutoff)
                )
            )
            .limit(100);

        const carrierClaimBreaches = await db
            .select({
                id: carrierClaims.id,
                orderId: carrierClaims.orderId,
                updatedAt: carrierClaims.updatedAt,
            })
            .from(carrierClaims)
            .where(
                and(
                    inArray(carrierClaims.status, ["filed", "in_review"]),
                    or(
                        lt(carrierClaims.dueAt, now),
                        lt(carrierClaims.updatedAt, fortyFiveDayCutoff)
                    )
                )
            )
            .limit(100);

        const codReconciliation14 = await db
            .select({
                id: codReconciliationItems.orderId,
                itemId: codReconciliationItems.id,
                totalAmount: codReconciliationItems.codAmount,
                updatedAt: codReconciliationItems.updatedAt,
            })
            .from(codReconciliationItems)
            .where(
                and(
                    inArray(codReconciliationItems.status, [
                        "pending",
                        "missing",
                        "disputed",
                    ]),
                    lt(codReconciliationItems.updatedAt, fourteenDayCutoff),
                    gte(codReconciliationItems.updatedAt, thirtyDaysAgo)
                )
            )
            .limit(100);

        const codReconciliation30 = await db
            .select({
                id: codReconciliationItems.orderId,
                itemId: codReconciliationItems.id,
                totalAmount: codReconciliationItems.codAmount,
                updatedAt: codReconciliationItems.updatedAt,
            })
            .from(codReconciliationItems)
            .where(
                and(
                    inArray(codReconciliationItems.status, [
                        "pending",
                        "missing",
                        "disputed",
                    ]),
                    lt(codReconciliationItems.updatedAt, thirtyDaysAgo)
                )
            )
            .limit(100);

        const recentCodRuns = await db
            .select({ id: codReconciliationRuns.id })
            .from(codReconciliationRuns)
            .where(gte(codReconciliationRuns.runDate, sevenDayCutoff))
            .limit(1);
        const codReconciliationSkipped =
            now.getDay() === 5 && recentCodRuns.length === 0;

        const brandAckDelayRows = await db
            .select({
                orderId: orders.id,
                brandId: products.brandId,
            })
            .from(orders)
            .innerJoin(orderItems, eq(orderItems.orderId, orders.id))
            .innerJoin(products, eq(products.id, orderItems.productId))
            .where(
                and(
                    inArray(orders.status, ["pending", "processing"]),
                    isNull(orders.brandAcknowledgedAt),
                    lt(orders.createdAt, dayCutoff),
                    gte(orders.createdAt, fourteenDayCutoff)
                )
            )
            .limit(500);
        const brandAckDelayCounts = new Map<
            string,
            { brandId: string; orderIds: Set<string> }
        >();
        for (const row of brandAckDelayRows) {
            if (!row.brandId) continue;
            const current = brandAckDelayCounts.get(row.brandId) ?? {
                brandId: row.brandId,
                orderIds: new Set<string>(),
            };
            current.orderIds.add(row.orderId);
            brandAckDelayCounts.set(row.brandId, current);
        }
        const repeatedBrandAckDelays = Array.from(
            brandAckDelayCounts.values()
        ).filter((item) => item.orderIds.size >= 3);

        const pendingRefunds = await db
            .select({ id: refunds.id, createdAt: refunds.createdAt })
            .from(refunds)
            .where(
                and(
                    eq(refunds.status, "pending"),
                    lt(refunds.createdAt, twoDayCutoff)
                )
            )
            .limit(100);

        const failedRefunds = await db
            .select({
                id: refunds.id,
                updatedAt: refunds.updatedAt,
                failedReason: refunds.failedReason,
            })
            .from(refunds)
            .where(eq(refunds.status, "failed"))
            .limit(100);

        const autoApprovalReturnRequests = await db
            .select({
                id: orderReturnRequests.id,
                orderId: orderReturnRequests.orderId,
                createdAt: orderReturnRequests.createdAt,
            })
            .from(orderReturnRequests)
            .where(
                and(
                    eq(orderReturnRequests.status, "pending"),
                    eq(orderReturnRequests.requestType, "return"),
                    lt(orderReturnRequests.createdAt, twoDayCutoff)
                )
            )
            .limit(100);

        const failedPayments = await db
            .select({ id: orders.id, updatedAt: orders.updatedAt })
            .from(orders)
            .where(eq(orders.paymentStatus, "failed"))
            .limit(100);

        const contractExpiring = await db
            .select({
                id: brands.id,
                name: brands.name,
                contractExpiresAt: brands.contractExpiresAt,
            })
            .from(brands)
            .where(
                and(
                    isNotNull(brands.contractExpiresAt),
                    lt(brands.contractExpiresAt, thirtyDayCutoff)
                )
            )
            .limit(100);

        const certExpiring = await db
            .select({
                id: brandConfidentials.id,
                sustainabilityCertificateExpiresAt:
                    brandConfidentials.sustainabilityCertificateExpiresAt,
            })
            .from(brandConfidentials)
            .where(
                and(
                    isNotNull(
                        brandConfidentials.sustainabilityCertificateExpiresAt
                    ),
                    lt(
                        brandConfidentials.sustainabilityCertificateExpiresAt,
                        thirtyDayCutoff
                    )
                )
            )
            .limit(100);

        const lowInventory = await db
            .select({
                id: productVariants.id,
                sku: productVariants.sku,
                quantity: productVariants.quantity,
            })
            .from(productVariants)
            .where(
                and(
                    gte(productVariants.quantity, 0),
                    lt(productVariants.quantity, 5)
                )
            )
            .limit(100);

        for (const ticket of unassignedTickets) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "ticket_unassigned",
                severity: "warning",
                entityType: "support_ticket",
                entityId: ticket.id,
                title: "Ticket unassigned for more than 2 hours",
                message: `${ticket.title} needs an owner within 1 hour.`,
                ownerId: actorId,
                ownerRole: "support_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(ticket.createdAt.getTime() + 3 * HOUR),
                dedupeKey: `ticket:unassigned:${ticket.id}`,
                metadata: { source: "sla-check" },
            });
        }

        for (const ticket of [...staleAdminTickets, ...staleUserTickets]) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "ticket_unresponded_24h",
                severity: "critical",
                entityType: "support_ticket",
                entityId: ticket.id,
                title: "Ticket unresponded for more than 24 hours",
                message: `${ticket.title} has not moved within 24 hours.`,
                ownerId: actorId,
                ownerRole: "support_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(ticket.statusChangedAt!.getTime() + 28 * HOUR),
                dedupeKey: `ticket:stale:${ticket.id}`,
                metadata: { source: "sla-check" },
            });
        }

        for (const ticket of [
            ...adminFirstResponseBreaches,
            ...userFirstResponseBreaches,
        ]) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "support_first_response_breach",
                severity: "critical",
                entityType: "support_ticket",
                entityId: ticket.id,
                title: "Support first response SLA breached",
                message: `${ticket.title} missed the Chapter 3 first-response SLA.`,
                ownerId: actorId,
                ownerRole: "support_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: ticket.dueAt,
                dedupeKey: `support:first-response:${ticket.id}`,
                metadata: {
                    source: "sla-check",
                    dueAt: ticket.dueAt?.toISOString(),
                },
            });
        }

        for (const ticket of [
            ...adminResolutionBreaches,
            ...userResolutionBreaches,
        ]) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "support_resolution_breach",
                severity: "critical",
                entityType: "support_ticket",
                entityId: ticket.id,
                title: "Support resolution SLA breached",
                message: `${ticket.title} missed the Chapter 3 resolution SLA.`,
                ownerId: actorId,
                ownerRole: "support_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: ticket.dueAt,
                dedupeKey: `support:resolution:${ticket.id}`,
                metadata: {
                    source: "sla-check",
                    dueAt: ticket.dueAt?.toISOString(),
                },
            });
        }

        for (const ticket of missedCustomerUpdates) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "support_customer_update_breach",
                severity: "warning",
                entityType: "support_ticket",
                entityId: ticket.id,
                title: "Customer update SLA breached",
                message: `${ticket.title} needs a 24-hour customer update.`,
                ownerId: actorId,
                ownerRole: "support_manager",
                channels: ["admin", "email"],
                dueAt: ticket.dueAt,
                dedupeKey: `support:customer-update:${ticket.id}`,
                metadata: {
                    source: "sla-check",
                    dueAt: ticket.dueAt?.toISOString(),
                },
            });
        }

        for (const ticket of customerAutoCloseTickets) {
            checkedCount += 1;

            await db
                .update(userSupportTickets)
                .set({
                    status: "auto_closed",
                    resolutionCode: "RES_AUTOCLOSED_NO_RESPONSE",
                    closedAt: now,
                    resolvedAt: now,
                    statusChangedAt: now,
                    reopenAllowedUntil: new Date(now.getTime() + 14 * DAY),
                    updatedAt: now,
                })
                .where(eq(userSupportTickets.id, ticket.id));

            await this.writeAudit({
                userId: actorId,
                actionType: "ticket_auto_closed",
                entityType: "user_support_ticket",
                entityId: ticket.id,
                beforeValue: { status: "waiting_customer" },
                afterValue: {
                    status: "auto_closed",
                    resolutionCode: "RES_AUTOCLOSED_NO_RESPONSE",
                },
                reason: "customer_no_response_7_days",
            });
        }

        for (const order of brandAckAtRisk18) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "brand_ack_at_risk_18h",
                severity: "warning",
                entityType: "order",
                entityId: order.id,
                title: "Brand acknowledgement approaching SLA",
                message: `Order ${order.id} has crossed 18 hours without brand acknowledgement. Chase the brand before the 24-hour SLA breach.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email"],
                dueAt: new Date(order.createdAt.getTime() + DAY),
                dedupeKey: `order:brand-ack-risk:${order.id}`,
                metadata: { source: "sla-check", chapter: "order-ops" },
            });
        }

        for (const order of unackOrders24) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "order_unacknowledged_24h",
                severity:
                    now.getTime() - order.createdAt.getTime() > 2 * DAY
                        ? "critical"
                        : "warning",
                entityType: "order",
                entityId: order.id,
                title: "Order not acknowledged by brand",
                message: `Order ${order.id} has not been acknowledged within 24 hours.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(order.createdAt.getTime() + 28 * HOUR),
                dedupeKey: `order:unack:${order.id}`,
                metadata: { source: "sla-check" },
            });
        }

        for (const order of brandSilenceAutoCancels) {
            checkedCount += 1;
            breachCount += 1;

            await db
                .update(orders)
                .set({
                    status: "cancelled",
                    paymentStatus:
                        order.paymentStatus === "paid"
                            ? "refund_pending"
                            : order.paymentStatus,
                    cancellationReasonCode: "CAN_BRAND_NO_RESPONSE",
                    manualOverrideReason:
                        "Auto-cancelled by Order Ops SLA after brand silence for more than 48 hours.",
                    updatedAt: now,
                })
                .where(eq(orders.id, order.id));

            await this.writeAudit({
                userId: actorId,
                actionType: "order_auto_cancelled_brand_no_response",
                entityType: "order",
                entityId: order.id,
                beforeValue: {
                    status: order.status,
                    paymentStatus: order.paymentStatus,
                },
                afterValue: {
                    status: "cancelled",
                    paymentStatus:
                        order.paymentStatus === "paid"
                            ? "refund_pending"
                            : order.paymentStatus,
                    cancellationReasonCode: "CAN_BRAND_NO_RESPONSE",
                },
                reason: "brand_ack_sla_48h_breached",
                metadata: { source: "sla-check", chapter: "order-ops" },
            });

            await this.createAlert({
                type: "order_auto_cancelled_brand_no_response",
                severity: "critical",
                entityType: "order",
                entityId: order.id,
                title: "Order auto-cancelled after brand silence",
                message: `Order ${order.id} was auto-cancelled because the brand did not acknowledge within 48 hours. Refund follow-up is required for prepaid orders.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + 4 * HOUR),
                dedupeKey: `order:auto-cancel-brand-no-response:${order.id}`,
                metadata: {
                    source: "sla-check",
                    chapter: "order-ops",
                    cancellationReasonCode: "CAN_BRAND_NO_RESPONSE",
                },
            });
        }

        for (const order of stuckOrders) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "order_stuck_48h",
                severity: "critical",
                entityType: "order",
                entityId: order.id,
                title: "Order stuck with no movement",
                message: `Order ${order.id} has no status movement for more than 48 hours.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(order.updatedAt.getTime() + 52 * HOUR),
                dedupeKey: `order:stuck:${order.id}`,
                metadata: { source: "sla-check" },
            });
        }

        for (const order of stuckOrders72) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "stuck_order_customer_choice_due",
                severity: "critical",
                entityType: "order",
                entityId: order.id,
                title: "Customer choice message due for stuck order",
                message: `Order ${order.id} has been stuck in ${order.status} for more than 72 hours. Send the customer a wait/refund choice message.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + 4 * HOUR),
                dedupeKey: `order:stuck-72h:${order.id}`,
                metadata: { source: "sla-check", chapter: "order-ops" },
            });
        }

        for (const order of codFraudReviewBreaches) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "fraud_screening_breach",
                severity: "critical",
                entityType: "order",
                entityId: order.id,
                title: "COD fraud review SLA breached",
                message: `COD order ${order.id} has been awaiting fraud screening for more than 4 hours. Review risk signals and cancel with CAN_FRAUD_FLAG if needed.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + 2 * HOUR),
                dedupeKey: `order:cod-fraud-review:${order.id}`,
                metadata: {
                    source: "sla-check",
                    chapter: "order-ops",
                    fraudReviewId: order.reviewId,
                    totalAmount: order.totalAmount,
                },
            });
        }

        for (const shipment of staleTrackingShipments) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "shipment_tracking_stale_6h",
                severity: "warning",
                entityType: "order_shipment",
                entityId: shipment.id,
                title: "Shipment tracking update stale",
                message: `Shipment for order ${shipment.orderId} has not received a tracking update within 6 hours while ${shipment.status}. Check Delhivery/Shiprocket sync.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email"],
                dueAt: new Date(now.getTime() + 4 * HOUR),
                dedupeKey: `shipment:tracking-stale:${shipment.id}`,
                metadata: { source: "sla-check", chapter: "order-ops" },
            });
        }

        for (const shipment of rtoDispositionBreaches) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "rto_disposition_breach",
                severity: "critical",
                entityType: "rto_disposition",
                entityId: shipment.id,
                title: "RTO disposition pending beyond 7 days",
                message: `RTO disposition for order ${shipment.orderId} has been in ${shipment.status} beyond the 7-day SLA.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + 4 * HOUR),
                dedupeKey: `rto:disposition:${shipment.id}`,
                metadata: { source: "sla-check", chapter: "order-ops" },
            });
        }

        for (const request of returnQcBreaches) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "return_qc_breach",
                severity: "warning",
                entityType: "order_return_request",
                entityId: request.id,
                title: "Return QC pending beyond 48 hours",
                message: `Return request ${request.id} for order ${request.orderId} is still in quality check after 48 hours.`,
                ownerId: actorId,
                ownerRole: "support_manager",
                channels: ["admin", "email"],
                dueAt: new Date(now.getTime() + 4 * HOUR),
                dedupeKey: `return:qc-breach:${request.id}`,
                metadata: { source: "sla-check", chapter: "order-ops" },
            });
        }

        for (const shipment of carrierClaimBreaches) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "carrier_claim_45d_breach",
                severity: "critical",
                entityType: "carrier_claim",
                entityId: shipment.id,
                title: "Carrier claim pending beyond 45 days",
                message: `Carrier claim for order ${shipment.orderId} is pending beyond the 45-day SLA. Chase the carrier claim outcome.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + 4 * HOUR),
                dedupeKey: `carrier-claim:45d:${shipment.id}`,
                metadata: { source: "sla-check", chapter: "order-ops" },
            });
        }

        for (const order of codReconciliation14) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "cod_reconciliation_pending_14d",
                severity: "warning",
                entityType: "order",
                entityId: order.id,
                title: "COD reconciliation pending beyond 14 days",
                message: `Delivered COD order ${order.id} has not been cleared in the weekly reconciliation window.`,
                ownerId: actorId,
                ownerRole: "finance",
                channels: ["admin", "email"],
                dueAt: new Date(now.getTime() + 3 * DAY),
                dedupeKey: `order:cod-recon-14d:${order.id}`,
                metadata: {
                    source: "sla-check",
                    chapter: "order-ops",
                    codReconciliationItemId: order.itemId,
                    totalAmount: order.totalAmount,
                },
            });
        }

        for (const order of codReconciliation30) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "cod_reconciliation_pending_30d",
                severity: "critical",
                entityType: "order",
                entityId: order.id,
                title: "COD reconciliation pending beyond 30 days",
                message: `Delivered COD order ${order.id} has crossed the 30-day finance escalation threshold.`,
                ownerId: actorId,
                ownerRole: "finance",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + DAY),
                dedupeKey: `order:cod-recon-30d:${order.id}`,
                metadata: {
                    source: "sla-check",
                    chapter: "order-ops",
                    codReconciliationItemId: order.itemId,
                    totalAmount: order.totalAmount,
                },
            });
        }

        if (codReconciliationSkipped) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "cod_reconciliation_skipped",
                severity: "critical",
                entityType: "cod_reconciliation_run",
                entityId: new Date().toISOString().slice(0, 10),
                title: "COD reconciliation log missing",
                message:
                    "No COD reconciliation run was created in the last 7 days. Chapter 4 requires the Thursday 3 PM reconciliation session with AJ.",
                ownerId: actorId,
                ownerRole: "finance",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + 4 * HOUR),
                dedupeKey: `cod-recon:skipped:${new Date().toISOString().slice(0, 10)}`,
                metadata: { source: "sla-check", chapter: "order-ops" },
            });
        }

        for (const brand of repeatedBrandAckDelays) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "brand_ack_delay_pattern",
                severity: "critical",
                entityType: "brand",
                entityId: brand.brandId,
                title: "Repeated brand acknowledgement delays",
                message: `Brand ${brand.brandId} has ${brand.orderIds.size} orders delayed beyond acknowledgement SLA in the last 14 days. Escalate to KP.`,
                ownerId: actorId,
                ownerRole: "brand_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + DAY),
                dedupeKey: `brand:ack-delay-pattern:${brand.brandId}:${new Date().toISOString().slice(0, 10)}`,
                metadata: {
                    source: "sla-check",
                    chapter: "order-ops",
                    orderIds: Array.from(brand.orderIds),
                },
            });
        }

        for (const refund of pendingRefunds) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "refund_pending_48h",
                severity: "warning",
                entityType: "refund",
                entityId: refund.id,
                title: "Refund pending processing",
                message: `Refund ${refund.id} has been pending for more than 48 hours.`,
                ownerId: actorId,
                ownerRole: "support_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(refund.createdAt.getTime() + 52 * HOUR),
                dedupeKey: `refund:pending:${refund.id}`,
                metadata: { source: "sla-check" },
            });
        }

        for (const refund of failedRefunds) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "refund_failed",
                severity: "critical",
                entityType: "refund",
                entityId: refund.id,
                title: "Refund failed",
                message: `Refund ${refund.id} failed and needs AJ review.`,
                ownerId: actorId,
                ownerRole: "aj",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(refund.updatedAt.getTime() + 4 * HOUR),
                dedupeKey: `refund:failed:${refund.id}`,
                metadata: {
                    source: "sla-check",
                    failedReason: refund.failedReason ?? null,
                },
            });
        }

        for (const request of autoApprovalReturnRequests) {
            checkedCount += 1;
            breachCount += 1;

            const approved = await db
                .update(orderReturnRequests)
                .set({
                    status: "approved",
                    updatedAt: new Date(),
                })
                .where(eq(orderReturnRequests.id, request.id))
                .returning()
                .then((res) => res[0]);

            await this.writeAudit({
                userId: actorId,
                actionType: "return_request_auto_approved",
                entityType: "order_return_request",
                entityId: request.id,
                beforeValue: { status: "pending" },
                afterValue: {
                    status: approved?.status ?? "approved",
                    orderId: request.orderId,
                },
                reason: "brand_return_response_sla_48h_breached",
            });

            await this.createAlert({
                type: "return_auto_approved_48h",
                severity: "warning",
                entityType: "order_return_request",
                entityId: request.id,
                title: "Return auto-approved after brand silence",
                message: `Return request ${request.id} was auto-approved because the brand did not respond within 48 hours.`,
                ownerId: actorId,
                ownerRole: "support_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: new Date(now.getTime() + DAY),
                dedupeKey: `return:auto-approved:${request.id}`,
                metadata: {
                    source: "sla-check",
                    orderId: request.orderId,
                    createdAt: request.createdAt.toISOString(),
                },
            });
        }

        for (const order of failedPayments) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "payment_failed",
                severity: "warning",
                entityType: "order",
                entityId: order.id,
                title: "Payment failed",
                message: `Order ${order.id} has a failed payment status.`,
                ownerId: actorId,
                ownerRole: "order_manager",
                channels: ["admin", "email"],
                dueAt: new Date(order.updatedAt.getTime() + 4 * HOUR),
                dedupeKey: `payment:failed:${order.id}`,
                metadata: { source: "sla-check" },
            });
        }

        for (const brand of contractExpiring) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "brand_contract_expiring",
                severity: "warning",
                entityType: "brand",
                entityId: brand.id,
                title: "Brand contract expiring within 30 days",
                message: `${brand.name} contract expires on ${brand.contractExpiresAt?.toISOString().slice(0, 10)}.`,
                ownerId: actorId,
                ownerRole: "brand_manager",
                channels: ["admin", "email"],
                dueAt: brand.contractExpiresAt,
                dedupeKey: `brand:contract-expiry:${brand.id}`,
                metadata: { source: "sla-check" },
            });
        }

        for (const cert of certExpiring) {
            checkedCount += 1;
            breachCount += 1;
            const expired = cert.sustainabilityCertificateExpiresAt! < now;
            await this.createAlert({
                type: expired
                    ? "sustainability_cert_expired"
                    : "sustainability_cert_expiring",
                severity: expired ? "critical" : "warning",
                entityType: "brand_confidential",
                entityId: cert.id,
                title: expired
                    ? "Sustainability certificate expired"
                    : "Sustainability certificate expiring",
                message: `Certificate date: ${cert.sustainabilityCertificateExpiresAt?.toISOString().slice(0, 10)}.`,
                ownerId: actorId,
                ownerRole: "brand_manager",
                channels: ["admin", "email", "whatsapp"],
                dueAt: cert.sustainabilityCertificateExpiresAt,
                dedupeKey: `brand:cert-expiry:${cert.id}`,
                metadata: { source: "sla-check" },
            });
        }

        for (const variant of lowInventory) {
            checkedCount += 1;
            breachCount += 1;
            await this.createAlert({
                type: "inventory_below_threshold",
                severity: "info",
                entityType: "product_variant",
                entityId: variant.id,
                title: "Inventory below threshold",
                message: `${variant.sku ?? variant.id} has ${variant.quantity} units left.`,
                ownerId: actorId,
                ownerRole: "catalog_intern",
                channels: ["admin"],
                dueAt: new Date(now.getTime() + DAY),
                dedupeKey: `inventory:low:${variant.id}`,
                metadata: { source: "sla-check" },
            });
        }

        await this.escalateOverdueAlerts(actorId ?? "cron");

        return db
            .update(slaCheckRuns)
            .set({
                status: "completed",
                finishedAt: new Date(),
                checkedCount: String(checkedCount),
                breachCount: String(breachCount),
                metadata: {
                    unassignedTickets: unassignedTickets.length,
                    staleTickets:
                        staleAdminTickets.length + staleUserTickets.length,
                    supportFirstResponseBreaches:
                        adminFirstResponseBreaches.length +
                        userFirstResponseBreaches.length,
                    supportResolutionBreaches:
                        adminResolutionBreaches.length +
                        userResolutionBreaches.length,
                    missedCustomerUpdates: missedCustomerUpdates.length,
                    customerAutoClosed: customerAutoCloseTickets.length,
                    brandAckAtRisk18: brandAckAtRisk18.length,
                    unackOrders24: unackOrders24.length,
                    brandSilenceAutoCancels: brandSilenceAutoCancels.length,
                    stuckOrders: stuckOrders.length,
                    stuckOrders72: stuckOrders72.length,
                    codFraudReviewBreaches: codFraudReviewBreaches.length,
                    staleTrackingShipments: staleTrackingShipments.length,
                    rtoDispositionBreaches: rtoDispositionBreaches.length,
                    returnQcBreaches: returnQcBreaches.length,
                    carrierClaimBreaches: carrierClaimBreaches.length,
                    codReconciliation14: codReconciliation14.length,
                    codReconciliation30: codReconciliation30.length,
                    codReconciliationSkipped,
                    repeatedBrandAckDelays: repeatedBrandAckDelays.length,
                    pendingRefunds: pendingRefunds.length,
                    failedRefunds: failedRefunds.length,
                    autoApprovalReturnRequests:
                        autoApprovalReturnRequests.length,
                    failedPayments: failedPayments.length,
                    contractExpiring: contractExpiring.length,
                    certExpiring: certExpiring.length,
                    lowInventory: lowInventory.length,
                },
            })
            .where(eq(slaCheckRuns.id, run.id))
            .returning()
            .then((res) => res[0]);
    }

    async escalateOverdueAlerts(actorId: string) {
        const overdue = await db.query.monitoringAlerts.findMany({
            where: and(
                inArray(monitoringAlerts.status, ["open", "acknowledged"]),
                inArray(monitoringAlerts.severity, ["warning", "critical"]),
                lt(monitoringAlerts.acknowledgedDueAt, new Date())
            ),
            limit: 100,
        });

        for (const alert of overdue) {
            await this.updateAlertStatus("escalated", {
                alertId: alert.id,
                actorId,
                reasonCode: "auto_escalated_sla",
                notes: "Alert was not acknowledged within SLA.",
            });
        }

        return overdue.length;
    }

    async getDailyHealth() {
        const today = startOfDay();
        const weekStart = new Date(today.getTime() - 6 * DAY);
        const yesterday = new Date(today.getTime() - DAY);
        const fourHourCutoff = new Date(Date.now() - 4 * HOUR);
        const eighteenHourCutoff = new Date(Date.now() - 18 * HOUR);
        const dayCutoff = new Date(Date.now() - DAY);
        const twoDayCutoff = new Date(Date.now() - 2 * DAY);
        const sevenDayCutoff = new Date(Date.now() - 7 * DAY);
        const fourteenDayCutoff = new Date(Date.now() - 14 * DAY);

        const ordersPlaced24h = await db.$count(
            orders,
            gte(orders.createdAt, today)
        );
        const ordersUnack24h = await db.$count(
            orders,
            and(
                inArray(orders.status, ["pending", "processing"]),
                isNull(orders.brandAcknowledgedAt),
                lt(orders.createdAt, dayCutoff)
            )
        );
        const brandAckAtRisk18h = await db.$count(
            orders,
            and(
                inArray(orders.status, ["pending", "processing"]),
                isNull(orders.brandAcknowledgedAt),
                lt(orders.createdAt, eighteenHourCutoff),
                gte(orders.createdAt, dayCutoff)
            )
        );
        const codFraudReviewQueue = await db.$count(
            fraudReviews,
            and(
                eq(fraudReviews.status, "pending"),
                or(
                    lt(fraudReviews.dueAt, new Date()),
                    lt(fraudReviews.createdAt, fourHourCutoff)
                )
            )
        );
        const ordersShipped24h = await db.$count(
            orders,
            and(eq(orders.status, "shipped"), gte(orders.updatedAt, today))
        );
        const stuckOrders48h = await db.$count(
            orders,
            and(
                inArray(orders.status, ["pending", "processing"]),
                lt(orders.updatedAt, twoDayCutoff)
            )
        );
        const rtoInTransit = await db.$count(
            orderShipments,
            eq(orderShipments.status, "rto_initiated")
        );
        const rtoDispositionPending7d = await db.$count(
            rtoDispositions,
            and(
                inArray(rtoDispositions.status, ["pending", "recovering"]),
                or(
                    lt(rtoDispositions.dispositionDueAt, new Date()),
                    lt(rtoDispositions.createdAt, sevenDayCutoff)
                )
            )
        );
        const deliveredToday = await db.$count(
            orders,
            and(eq(orders.status, "delivered"), gte(orders.updatedAt, today))
        );
        const failedDeliveryToday = await db.$count(
            orderShipments,
            and(
                eq(orderShipments.status, "failed"),
                gte(orderShipments.updatedAt, today)
            )
        );
        const pendingCodAmount = await db
            .select({
                amount: sql<number>`coalesce(sum(${codReconciliationItems.codAmount} - ${codReconciliationItems.remittedAmount}), 0)`,
            })
            .from(codReconciliationItems)
            .where(
                and(
                    inArray(codReconciliationItems.status, [
                        "pending",
                        "missing",
                        "disputed",
                        "short_paid",
                    ]),
                    lt(codReconciliationItems.updatedAt, fourteenDayCutoff)
                )
            )
            .then((res) => res[0]?.amount ?? 0);
        const ordersPlacedYesterday = await db.$count(
            orders,
            and(gte(orders.createdAt, yesterday), lt(orders.createdAt, today))
        );
        const rtoRateSpike =
            ordersPlacedYesterday > 0 &&
            rtoInTransit / ordersPlacedYesterday > 0.2
                ? "review"
                : "normal";
        const openAlerts = await db.$count(
            monitoringAlerts,
            ne(monitoringAlerts.status, "resolved")
        );
        const criticalAlerts = await db.$count(
            monitoringAlerts,
            and(
                eq(monitoringAlerts.severity, "critical"),
                ne(monitoringAlerts.status, "resolved")
            )
        );
        const openAdminTickets = await db.$count(
            supportTickets,
            inArray(supportTickets.status, ACTIVE_SUPPORT_STATUSES)
        );
        const openUserTickets = await db.$count(
            userSupportTickets,
            inArray(userSupportTickets.status, ACTIVE_SUPPORT_STATUSES)
        );
        const agedAdminTickets = await db.$count(
            supportTickets,
            and(
                inArray(supportTickets.status, ACTIVE_SUPPORT_STATUSES),
                lt(supportTickets.statusChangedAt, dayCutoff)
            )
        );
        const agedUserTickets = await db.$count(
            userSupportTickets,
            and(
                inArray(userSupportTickets.status, ACTIVE_SUPPORT_STATUSES),
                lt(userSupportTickets.statusChangedAt, dayCutoff)
            )
        );
        const pendingRefunds = await db.$count(
            refunds,
            eq(refunds.status, "pending")
        );
        const failedPayments = await db.$count(
            orders,
            eq(orders.paymentStatus, "failed")
        );
        const pendingBrandRequests = await db.$count(
            brandRequests,
            eq(brandRequests.status, "pending")
        );
        const weeklyOrders = await db.$count(
            orders,
            gte(orders.createdAt, weekStart)
        );
        const activeBrands = await db.$count(brands, eq(brands.isActive, true));
        const inactiveOrPendingBrands = await db.$count(
            brands,
            or(
                eq(brands.isActive, false),
                ne(brands.confidentialVerificationStatus, "approved")
            )
        );
        const weeklyBusiness = await db
            .select({
                gmv: sql<number>`coalesce(sum(${orders.totalAmount}), 0)`,
                orderCount: sql<number>`count(${orders.id})`,
                newCustomers: sql<number>`count(distinct ${orders.userId})`,
                aov: sql<number>`case when count(${orders.id}) = 0 then 0 else coalesce(sum(${orders.totalAmount}), 0) / count(${orders.id}) end`,
            })
            .from(orders)
            .where(gte(orders.createdAt, weekStart))
            .then((res) => res[0]);
        const pendingRefundAmount = await db
            .select({
                amount: sql<number>`coalesce(sum(${refunds.amount}), 0)`,
            })
            .from(refunds)
            .where(eq(refunds.status, "pending"))
            .then((res) => res[0]?.amount ?? 0);

        const status: "green" | "amber" | "red" =
            criticalAlerts > 0 || stuckOrders48h > 0
                ? "red"
                : openAlerts > 0 || pendingRefunds > 0
                  ? "amber"
                  : "green";

        return {
            status,
            metrics: {
                ordersPlaced24h,
                brandAckAtRisk18h,
                ordersUnacknowledged24h: ordersUnack24h,
                codFraudReviewQueue,
                ordersShipped24h,
                stuckOrders48h,
                rtoInTransit,
                rtoDispositionPending7d,
                pendingCodAmount,
                deliveredToday,
                failedDeliveryToday,
                rtoRateSpike,
                openTickets: openAdminTickets + openUserTickets,
                ticketsAged24h: agedAdminTickets + agedUserTickets,
                refundsPendingProcessing: pendingRefunds,
                refundsPendingQc: pendingRefunds,
                failedPayments,
                brandNonResponseCases: pendingBrandRequests,
                platformUptime24h: criticalAlerts > 0 ? "review" : "100%",
                ordersWtd: weeklyOrders,
                gmvWtd: weeklyBusiness.gmv ?? 0,
                aovWtd: weeklyBusiness.aov ?? 0,
                newCustomersWtd: weeklyBusiness.newCustomers ?? 0,
                activeBrands,
                inactiveOrPendingBrands,
                pendingRefundAmount,
                openAlerts,
                criticalAlerts,
            },
        };
    }

    async saveDailySnapshot(actorId?: string | null) {
        const snapshotDate = new Date().toISOString().slice(0, 10);
        const health = await this.getDailyHealth();
        const existing = await db.query.dailyHealthSnapshots.findFirst({
            where: eq(dailyHealthSnapshots.snapshotDate, snapshotDate),
        });
        await this.writeAudit({
            userId: actorId,
            actionType: "daily_health_snapshot_generated",
            entityType: "daily_health_snapshot",
            entityId: snapshotDate,
            afterValue: health.metrics,
            reason: "daily_health_evidence",
        });

        if (existing) {
            return db
                .update(dailyHealthSnapshots)
                .set({
                    metrics: health.metrics,
                    status: health.status,
                    generatedBy: actorId,
                })
                .where(eq(dailyHealthSnapshots.id, existing.id))
                .returning()
                .then((res) => res[0]);
        }

        return db
            .insert(dailyHealthSnapshots)
            .values({
                snapshotDate,
                metrics: health.metrics,
                status: health.status,
                generatedBy: actorId,
            })
            .returning()
            .then((res) => res[0]);
    }

    async generateWeeklyPack(actorId?: string | null) {
        const end = startOfDay();
        const start = new Date(end.getTime() - 6 * DAY);
        const weekStart = start.toISOString().slice(0, 10);
        const weekEnd = end.toISOString().slice(0, 10);
        const health = await this.getDailyHealth();
        const actionItems = [
            health.metrics.criticalAlerts
                ? "Resolve critical monitoring alerts before founder review."
                : "Confirm open alerts are owned.",
            health.metrics.ticketsAged24h
                ? "Clear support tickets aged over 24 hours."
                : "Keep ticket first response SLA green.",
            health.metrics.ordersUnacknowledged24h
                ? "Chase brands on unacknowledged orders."
                : "No brand acknowledgement backlog.",
        ];

        const existing = await db.query.weeklyReportingPacks.findFirst({
            where: and(
                eq(weeklyReportingPacks.weekStart, weekStart),
                eq(weeklyReportingPacks.weekEnd, weekEnd)
            ),
        });

        const values = {
            executiveSnapshot: `System status is ${health.status}. GMV WTD: ${health.metrics.gmvWtd}. Orders WTD: ${health.metrics.ordersWtd}. New customers WTD: ${health.metrics.newCustomersWtd}. Open alerts: ${health.metrics.openAlerts}. Open tickets: ${health.metrics.openTickets}.`,
            actionItems,
            metrics: {
                executiveSnapshot: health.metrics,
                operationalMetrics: {
                    slaHitRate: health.metrics.openAlerts ? "review" : "green",
                    ticketsAged24h: health.metrics.ticketsAged24h,
                    refundsPendingProcessing:
                        health.metrics.refundsPendingProcessing,
                },
                financialSnapshot: {
                    gmvWtd: health.metrics.gmvWtd,
                    aovWtd: health.metrics.aovWtd,
                    refundsPendingProcessing:
                        health.metrics.refundsPendingProcessing,
                    pendingRefundAmount: health.metrics.pendingRefundAmount,
                    failedPayments: health.metrics.failedPayments,
                },
                brandHealth: {
                    activeBrands: health.metrics.activeBrands,
                    inactiveOrPendingBrands:
                        health.metrics.inactiveOrPendingBrands,
                    brandNonResponseCases: health.metrics.brandNonResponseCases,
                },
            },
            generatedBy: actorId,
        };

        await this.writeAudit({
            userId: actorId,
            actionType: "weekly_pack_generated",
            entityType: "weekly_reporting_pack",
            entityId: `${weekStart}:${weekEnd}`,
            afterValue: values,
            reason: "friday_weekly_review_pack",
        });

        if (existing) {
            return db
                .update(weeklyReportingPacks)
                .set(values)
                .where(eq(weeklyReportingPacks.id, existing.id))
                .returning()
                .then((res) => res[0]);
        }

        return db
            .insert(weeklyReportingPacks)
            .values({ weekStart, weekEnd, ...values })
            .returning()
            .then((res) => res[0]);
    }

    async getBrandHealth() {
        const now = new Date();
        const thirtyDaysAgo = new Date(now.getTime() - 30 * DAY);
        const thirtyDaysFromNow = new Date(now.getTime() + 30 * DAY);

        const activeBrands = await db.$count(brands, eq(brands.isActive, true));
        const pausedBrands = await db.$count(
            brands,
            eq(brands.isActive, false)
        );
        const pendingVerification = await db.$count(
            brands,
            ne(brands.confidentialVerificationStatus, "approved")
        );
        const activeProducts = await db.$count(
            products,
            and(
                eq(products.isActive, true),
                eq(products.isDeleted, false),
                eq(products.isPublished, true)
            )
        );
        const lowInventoryVariants = await db.$count(
            productVariants,
            and(
                gte(productVariants.quantity, 0),
                lt(productVariants.quantity, 5)
            )
        );
        const certExpiring30d = await db.$count(
            brandConfidentials,
            and(
                isNotNull(
                    brandConfidentials.sustainabilityCertificateExpiresAt
                ),
                lt(
                    brandConfidentials.sustainabilityCertificateExpiresAt,
                    thirtyDaysFromNow
                )
            )
        );
        const contractExpiring30d = await db.$count(
            brands,
            and(
                isNotNull(brands.contractExpiresAt),
                lt(brands.contractExpiresAt, thirtyDaysFromNow)
            )
        );
        const supportTickets30d = await db.$count(
            supportTickets,
            gte(supportTickets.createdAt, thirtyDaysAgo)
        );
        const brandsWithOrders30d = await db
            .select({
                count: sql<number>`count(distinct ${products.brandId})`,
            })
            .from(orderItems)
            .innerJoin(products, eq(orderItems.productId, products.id))
            .innerJoin(orders, eq(orderItems.orderId, orders.id))
            .where(gte(orders.createdAt, thirtyDaysAgo))
            .then((res) => res[0]?.count ?? 0);

        return {
            activeBrands,
            pausedBrands,
            pendingVerification,
            activeProducts,
            lowInventoryVariants,
            certExpiring30d,
            contractExpiring30d,
            supportTickets30d,
            brandsWithOrders30d,
            brandsWithNoOrders30d: Math.max(
                0,
                activeBrands - Number(brandsWithOrders30d)
            ),
        };
    }

    async getMarketingPerformance() {
        const today = startOfDay();
        const weekStart = new Date(today.getTime() - 6 * DAY);
        const monthStart = new Date(today.getFullYear(), today.getMonth(), 1);

        const week = await db
            .select({
                gmv: sql<number>`coalesce(sum(${orders.totalAmount}), 0)`,
                orders: sql<number>`count(${orders.id})`,
                customers: sql<number>`count(distinct ${orders.userId})`,
            })
            .from(orders)
            .where(gte(orders.createdAt, weekStart))
            .then((res) => res[0]);
        const month = await db
            .select({
                gmv: sql<number>`coalesce(sum(${orders.totalAmount}), 0)`,
                orders: sql<number>`count(${orders.id})`,
                customers: sql<number>`count(distinct ${orders.userId})`,
            })
            .from(orders)
            .where(gte(orders.createdAt, monthStart))
            .then((res) => res[0]);

        return {
            gmvWtd: week.gmv ?? 0,
            ordersWtd: week.orders ?? 0,
            customersWtd: week.customers ?? 0,
            gmvMtd: month.gmv ?? 0,
            ordersMtd: month.orders ?? 0,
            customersMtd: month.customers ?? 0,
            adSpendIntegration: "pending",
            cacIntegration: "pending",
            roasIntegration: "pending",
        };
    }

    async getMonthlyStrategic() {
        const now = new Date();
        const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
        const lastMonthStart = new Date(
            now.getFullYear(),
            now.getMonth() - 1,
            1
        );

        const current = await db
            .select({
                gmv: sql<number>`coalesce(sum(${orders.totalAmount}), 0)`,
                orderCount: sql<number>`count(${orders.id})`,
                customerCount: sql<number>`count(distinct ${orders.userId})`,
            })
            .from(orders)
            .where(gte(orders.createdAt, monthStart))
            .then((res) => res[0]);
        const lastMonth = await db
            .select({
                gmv: sql<number>`coalesce(sum(${orders.totalAmount}), 0)`,
                orderCount: sql<number>`count(${orders.id})`,
                customerCount: sql<number>`count(distinct ${orders.userId})`,
            })
            .from(orders)
            .where(
                and(
                    gte(orders.createdAt, lastMonthStart),
                    lt(orders.createdAt, monthStart)
                )
            )
            .then((res) => res[0]);
        const refundCount = await db.$count(
            refunds,
            gte(refunds.createdAt, monthStart)
        );
        const complianceExportsThisMonth = await db.$count(
            complianceExportRuns,
            gte(complianceExportRuns.createdAt, monthStart)
        );
        const openCriticalAlerts = await db.$count(
            monitoringAlerts,
            and(
                eq(monitoringAlerts.severity, "critical"),
                ne(monitoringAlerts.status, "resolved")
            )
        );

        return {
            currentMonth: current,
            previousMonth: lastMonth,
            refundRate:
                Number(current.orderCount ?? 0) === 0
                    ? 0
                    : Number(refundCount) / Number(current.orderCount),
            complianceExportsThisMonth,
            openCriticalAlerts,
            cohortRetentionIntegration: "pending",
            runwayIntegration: "pending",
        };
    }

    async buildComplianceExport(
        exportMonth: string,
        exportType: string
    ): Promise<ComplianceExportBuild> {
        const { start, end } = monthWindow(exportMonth);
        const auditHeaders = [
            "timestampUtc",
            "userId",
            "actionType",
            "entityType",
            "entityId",
            "reason",
        ];
        const refundHeaders = [
            "id",
            "orderId",
            "status",
            "amount",
            "reasonCode",
            "createdAt",
            "updatedAt",
        ];
        const auditByTypes = async (types: string[]) =>
            db
                .select({
                    timestampUtc: auditLogs.timestampUtc,
                    userId: auditLogs.userId,
                    actionType: auditLogs.actionType,
                    entityType: auditLogs.entityType,
                    entityId: auditLogs.entityId,
                    reason: auditLogs.reason,
                })
                .from(auditLogs)
                .where(
                    and(
                        gte(auditLogs.timestampUtc, start),
                        lt(auditLogs.timestampUtc, end),
                        inArray(auditLogs.entityType, types)
                    )
                );

        if (exportType === "refunds") {
            const rows = await db
                .select({
                    id: refunds.id,
                    orderId: refunds.orderId,
                    status: refunds.status,
                    amount: refunds.amount,
                    reasonCode: refunds.reasonCode,
                    createdAt: refunds.createdAt,
                    updatedAt: refunds.updatedAt,
                })
                .from(refunds)
                .where(
                    and(
                        gte(refunds.createdAt, start),
                        lt(refunds.createdAt, end)
                    )
                );
            return {
                rows,
                csv: toCsv(rows, refundHeaders),
                headers: refundHeaders,
                files: [
                    {
                        name: `${exportMonth}-refund-audit.csv`,
                        rowCount: rows.length,
                        headers: refundHeaders,
                    },
                ],
            };
        }

        const exportMap: Record<string, string[]> = {
            "brand-actions": ["brand", "brand_request", "brand_confidential"],
            "access-changes": ["user", "role", "user_role", "access_review"],
            "manual-overrides": ["manual_override", "order", "refund"],
            "sustainability-claims": ["product", "brand_confidential"],
            "data-deletion-requests": [
                "customer_account",
                "data_deletion_request",
            ],
            "customer-escalations": ["support_ticket", "user_support_ticket"],
            alerts: ["monitoring_alert", "alert"],
        };
        const rows = await auditByTypes(
            exportMap[exportType] ?? exportMap.alerts
        );
        return {
            rows,
            csv: toCsv(rows, auditHeaders),
            headers: auditHeaders,
            files: [
                {
                    name: `${exportMonth}-${exportType}.csv`,
                    rowCount: rows.length,
                    headers: auditHeaders,
                },
            ],
        };
    }

    async generateComplianceExport(
        exportMonth: string,
        exportType: string,
        actorId?: string | null
    ) {
        const { start, end } = monthWindow(exportMonth);
        const built = await this.buildComplianceExport(exportMonth, exportType);
        const retentionUntil = addYears(end, 7);
        const run = await db
            .insert(complianceExportRuns)
            .values({
                exportMonth,
                exportType,
                generatedBy: actorId,
                rowCount: String(built.rows.length),
                filters: { start: start.toISOString(), end: end.toISOString() },
                metadata: {
                    generatedFrom: "monitoring-sla",
                    retention: "7 years",
                },
                files: built.files,
                retentionUntil,
            })
            .returning()
            .then((res) => res[0]);

        await db.insert(complianceExportFiles).values(
            built.files.map((file) => ({
                exportRunId: run.id,
                fileName: file.name,
                rowCount: String(file.rowCount),
                metadata: {
                    downloadable: true,
                    contentPreview: built.csv.slice(0, 5000),
                },
            }))
        );

        await this.writeAudit({
            userId: actorId,
            actionType: "compliance_export_generated",
            entityType: "compliance_export",
            entityId: run.id,
            afterValue: {
                exportMonth,
                exportType,
                rowCount: built.rows.length,
                files: built.files,
            },
            reason: "monthly_compliance_evidence",
        });

        return run;
    }

    async generateAccessReview(actorId?: string | null) {
        const now = new Date();
        const quarter = Math.floor(now.getMonth() / 3) + 1;
        const reviewPeriod = `${now.getFullYear()}-Q${quarter}`;
        const existing = await db.query.accessReviewRuns.findFirst({
            where: eq(accessReviewRuns.reviewPeriod, reviewPeriod),
        });
        if (existing) return existing;

        const review = await db
            .insert(accessReviewRuns)
            .values({ reviewPeriod, generatedBy: actorId, status: "in_review" })
            .returning()
            .then((res) => res[0]);

        const activeUsers = await db
            .select({
                id: users.id,
                email: users.email,
                roleCount: sql<number>`count(${userRoles.id})`,
            })
            .from(users)
            .leftJoin(userRoles, eq(userRoles.userId, users.id))
            .groupBy(users.id)
            .limit(500);

        if (activeUsers.length) {
            await db.insert(accessReviewItems).values(
                activeUsers.map((user) => ({
                    reviewId: review.id,
                    userId: user.id,
                    email: user.email,
                    roleSummary: `${user.roleCount ?? 0} assigned roles`,
                    decision: "pending" as const,
                }))
            );
        }

        await this.writeAudit({
            userId: actorId,
            actionType: "access_review_generated",
            entityType: "access_review",
            entityId: review.id,
            afterValue: { reviewPeriod, itemCount: activeUsers.length },
            reason: "quarterly_access_review",
        });

        return review;
    }

    async getRecentEvidence() {
        const [runs, packs, exports, reviews, snapshots, audit] =
            await Promise.all([
                db.query.slaCheckRuns.findMany({
                    orderBy: [desc(slaCheckRuns.createdAt)],
                    limit: 5,
                }),
                db.query.weeklyReportingPacks.findMany({
                    orderBy: [desc(weeklyReportingPacks.createdAt)],
                    limit: 5,
                }),
                db.query.complianceExportRuns.findMany({
                    orderBy: [desc(complianceExportRuns.createdAt)],
                    limit: 5,
                }),
                db.query.accessReviewRuns.findMany({
                    orderBy: [desc(accessReviewRuns.createdAt)],
                    limit: 5,
                }),
                db.query.dailyHealthSnapshots.findMany({
                    orderBy: [desc(dailyHealthSnapshots.createdAt)],
                    limit: 5,
                }),
                db.query.auditLogs.findMany({
                    orderBy: [desc(auditLogs.timestampUtc)],
                    limit: 5,
                }),
            ]);

        return { runs, packs, exports, reviews, snapshots, audit };
    }
}

export const monitoringSlaQueries = new MonitoringSlaQuery();
